development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  database: fender_development
  username: root

production:
  # あとで設定
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8
  database: fender_production
  username: root
  password: Snsn0803+
  host: 118.27.9.161
